module.exports = {
  type: 'chicken',
  label: 'Poultry (Chicken)',
  breeds: ['broiler', 'layer', 'cockerel'],

  feedSchedule: {
    broiler: [
      { weekStart: 1, weekEnd: 2, phase: 'Starter',  feedType: 'Chick Mash',    gPerBirdPerDay: 45  },
      { weekStart: 3, weekEnd: 4, phase: 'Grower',   feedType: 'Growers Mash',  gPerBirdPerDay: 85  },
      { weekStart: 5, weekEnd: 6, phase: 'Finisher', feedType: 'Finisher Mash', gPerBirdPerDay: 125 },
    ],
    layer: [
      { weekStart: 1,  weekEnd: 8,  phase: 'Chick',  feedType: 'Chick Mash',   gPerBirdPerDay: 30  },
      { weekStart: 9,  weekEnd: 18, phase: 'Grower', feedType: 'Growers Mash', gPerBirdPerDay: 80  },
      { weekStart: 19, weekEnd: 72, phase: 'Layer',  feedType: 'Layers Mash',  gPerBirdPerDay: 115 },
    ],
    cockerel: [
      { weekStart: 1,  weekEnd: 4,  phase: 'Starter',  feedType: 'Chick Mash',    gPerBirdPerDay: 40  },
      { weekStart: 5,  weekEnd: 8,  phase: 'Grower',   feedType: 'Growers Mash',  gPerBirdPerDay: 90  },
      { weekStart: 9,  weekEnd: 12, phase: 'Finisher', feedType: 'Finisher Mash', gPerBirdPerDay: 120 },
    ],
  },

  brandGuide: {
    Starter: {
      proteinPercent: '22–24%',
      warning: 'Never buy feed with no ingredient list. Check NAFDAC registration number on the bag.',
      buyingTips: [
        'Check protein content — minimum 22% for broiler starter',
        'Look for Lysine and Methionine on the label — essential for fast growth',
        'Check manufacturing date — never buy feed older than 3 months',
        'Smell the feed — good feed smells like grain, never sour or musty',
        'Buy from a cool dry store — heat and moisture cause mould and aflatoxin poisoning',
      ],
      brands: [
        {
          name:        'Vital Feed',
          product:     'Vital Broiler Starter',
          ingredients: ['Maize', 'Soya', 'Fish Meal', 'Lysine', 'Methionine', 'Vitamins A/D3/E'],
          priceRange:  '₦7,500 – ₦8,500 per 25kg bag',
          whereToBuy:  'Agrovets, Vital Feed agents, AgroMall online',
          rating:      5,
        },
        {
          name:        'Hybrid Feeds',
          product:     'Hybrid Broiler Chick Mash',
          ingredients: ['Maize', 'Groundnut Cake', 'Fish Meal', 'Premix', 'DCP'],
          priceRange:  '₦7,000 – ₦8,000 per 25kg bag',
          whereToBuy:  'Feed stores nationwide',
          rating:      4,
        },
        {
          name:        'Olam Feeds',
          product:     'Futura Broiler Starter',
          ingredients: ['Maize', 'Soya Bean Meal', 'Vitamins', 'Amino acids'],
          priceRange:  '₦8,000 – ₦9,000 per 25kg bag',
          whereToBuy:  'Olam distributors, AgroMall',
          rating:      4,
        },
        {
          name:        'Top Feeds',
          product:     'Top Broiler Starter',
          ingredients: ['Maize', 'Soybean', 'Lysine', 'Methionine', 'Coccidiostat'],
          priceRange:  '₦7,200 – ₦7,800 per 25kg bag',
          whereToBuy:  'Top Feeds agents, open market',
          rating:      4,
        },
      ],
    },

    Grower: {
      proteinPercent: '20–22%',
      warning: 'Check for DCP (Dicalcium Phosphate) on the label — needed for bone development at this stage.',
      buyingTips: [
        'Protein should be 20–22% — lower than starter because birds are bigger now',
        'Must contain DCP for strong bone development',
        'Check expiry date and storage condition at the shop',
        'Texture should be uniform dry pellets or mash — no clumps or wet spots',
        'Buy in bulk if you have storage — 10+ bags saves cost per kg',
      ],
      brands: [
        {
          name:        'Vital Feed',
          product:     'Vital Broiler Grower',
          ingredients: ['Maize', 'Soya', 'Fish Meal', 'Methionine', 'Minerals'],
          priceRange:  '₦7,000 – ₦8,000 per 25kg bag',
          whereToBuy:  'Agrovets, Vital Feed agents',
          rating:      5,
        },
        {
          name:        'Hybrid Feeds',
          product:     'Hybrid Growers Mash',
          ingredients: ['Maize', 'Groundnut Cake', 'Soya', 'DCP', 'Premix'],
          priceRange:  '₦6,800 – ₦7,500 per 25kg bag',
          whereToBuy:  'Feed stores nationwide',
          rating:      4,
        },
        {
          name:        'Olam Feeds',
          product:     'Futura Broiler Grower',
          ingredients: ['Maize', 'Soybean Meal', 'Vitamins', 'Phosphorus'],
          priceRange:  '₦7,500 – ₦8,500 per 25kg bag',
          whereToBuy:  'Olam distributors',
          rating:      4,
        },
        {
          name:        'Top Feeds',
          product:     'Top Broiler Grower',
          ingredients: ['Maize', 'Soybean', 'Amino acids', 'Coccidiostat'],
          priceRange:  '₦6,900 – ₦7,600 per 25kg bag',
          whereToBuy:  'Top Feeds agents',
          rating:      4,
        },
      ],
    },

    Finisher: {
      proteinPercent: '18–20%',
      warning: 'CRITICAL — Finisher feed must be coccidiostat-free or have a withdrawal period stated. You are close to slaughter. Medication residues in meat is a food safety issue.',
      buyingTips: [
        'Protein 18–20% — lowest of the three phases',
        'Must be coccidiostat-FREE or within withdrawal period before slaughter',
        'Higher energy content than grower — helps birds put on final weight fast',
        'Do not switch to finisher too early — wait until week 5',
        'Check the withdrawal period on the bag — usually 5–7 days before slaughter',
      ],
      brands: [
        {
          name:        'Vital Feed',
          product:     'Vital Broiler Finisher',
          ingredients: ['Maize', 'Soya', 'Wheat Offal', 'Vitamins', 'Low coccidiostat'],
          priceRange:  '₦6,500 – ₦7,500 per 25kg bag',
          whereToBuy:  'Agrovets, Vital Feed agents',
          rating:      5,
        },
        {
          name:        'Hybrid Feeds',
          product:     'Hybrid Finisher Mash',
          ingredients: ['Maize', 'Groundnut', 'Soya', 'Minerals', 'Premix'],
          priceRange:  '₦6,500 – ₦7,200 per 25kg bag',
          whereToBuy:  'Feed stores nationwide',
          rating:      4,
        },
        {
          name:        'Olam Feeds',
          product:     'Futura Broiler Finisher',
          ingredients: ['Maize', 'Soybean', 'Energy boosters', 'Vitamins'],
          priceRange:  '₦7,000 – ₦8,000 per 25kg bag',
          whereToBuy:  'Olam distributors',
          rating:      4,
        },
        {
          name:        'Top Feeds',
          product:     'Top Broiler Finisher',
          ingredients: ['Maize', 'Soybean', 'Wheat offal', 'Amino acids'],
          priceRange:  '₦6,500 – ₦7,000 per 25kg bag',
          whereToBuy:  'Top Feeds agents',
          rating:      4,
        },
      ],
    },

    Chick: {
      proteinPercent: '20–22%',
      warning: 'Coccidiostat is essential at this stage — young chicks are highly vulnerable to coccidiosis.',
      buyingTips: [
        'Must contain coccidiostat — young chicks are very vulnerable',
        'Protein 20–22% for healthy early growth',
        'Feed must be fine mash texture — chicks cannot eat large pellets',
        'Keep feed dry at all times — wet feed causes disease in young chicks',
        'Do not mix with grower or layer feed at this stage',
      ],
      brands: [
        {
          name:        'Vital Feed',
          product:     'Vital Chick Mash',
          ingredients: ['Maize', 'Soya', 'Fish Meal', 'Coccidiostat', 'Vitamins'],
          priceRange:  '₦7,000 – ₦8,500 per 25kg bag',
          whereToBuy:  'Agrovets, Vital Feed agents',
          rating:      5,
        },
        {
          name:        'Hybrid Feeds',
          product:     'Hybrid Chick Starter',
          ingredients: ['Maize', 'Groundnut Cake', 'Fish Meal', 'Premix', 'Coccidiostat'],
          priceRange:  '₦7,000 – ₦8,000 per 25kg bag',
          whereToBuy:  'Feed stores nationwide',
          rating:      4,
        },
      ],
    },

    Layer: {
      proteinPercent: '16–17%',
      warning: 'Do NOT give layer mash before week 18. High calcium before laying age causes kidney damage and early death.',
      buyingTips: [
        'Calcium content must be 3.5–4% — this is what makes strong eggshells',
        'Do NOT give to birds younger than 18 weeks — kidney damage risk',
        'Protein 16–17% — lower than grower but calcium is higher',
        'Ensure fresh supply — layer mash can go stale fast in humid weather',
        'Supplement with oyster shell or limestone grit for extra calcium if shells are thin',
      ],
      brands: [
        {
          name:        'Vital Feed',
          product:     'Vital Layer Mash',
          ingredients: ['Maize', 'Soya', 'Limestone', 'DCP', 'Vitamins', 'Premix'],
          priceRange:  '₦6,800 – ₦8,000 per 25kg bag',
          whereToBuy:  'Agrovets, Vital Feed agents',
          rating:      5,
        },
        {
          name:        'Hybrid Feeds',
          product:     'Hybrid Layer Mash',
          ingredients: ['Maize', 'Groundnut Cake', 'Soya', 'Limestone', 'Premix'],
          priceRange:  '₦6,500 – ₦7,500 per 25kg bag',
          whereToBuy:  'Feed stores nationwide',
          rating:      4,
        },
        {
          name:        'Top Feeds',
          product:     'Top Layer Mash',
          ingredients: ['Maize', 'Soybean', 'Calcium carbonate', 'Vitamins'],
          priceRange:  '₦6,800 – ₦7,800 per 25kg bag',
          whereToBuy:  'Top Feeds agents',
          rating:      4,
        },
      ],
    },
  },

  vaccinationSchedule: {
    broiler: [
      { dayOffset: 7,  name: 'Newcastle Disease (Lasota)', method: 'Eye drop / drinking water' },
      { dayOffset: 14, name: 'Gumboro (IBD)',              method: 'Drinking water'             },
      { dayOffset: 21, name: 'Newcastle Booster',          method: 'Drinking water'             },
      { dayOffset: 28, name: 'Gumboro Booster',            method: 'Drinking water'             },
    ],
    layer: [
      { dayOffset: 7,   name: 'Newcastle Disease (Lasota)', method: 'Eye drop'       },
      { dayOffset: 14,  name: 'Gumboro (IBD)',              method: 'Drinking water' },
      { dayOffset: 21,  name: 'Newcastle Booster',          method: 'Drinking water' },
      { dayOffset: 42,  name: 'Fowl Pox',                   method: 'Wing web stab'  },
      { dayOffset: 56,  name: 'Newcastle (Komarov)',         method: 'Injection'      },
      { dayOffset: 112, name: 'Newcastle 6-month Booster',  method: 'Drinking water' },
    ],
    cockerel: [
      { dayOffset: 7,  name: 'Newcastle Disease (Lasota)', method: 'Eye drop'       },
      { dayOffset: 14, name: 'Gumboro (IBD)',              method: 'Drinking water' },
      { dayOffset: 21, name: 'Newcastle Booster',          method: 'Drinking water' },
      { dayOffset: 42, name: 'Fowl Pox',                   method: 'Wing web stab'  },
    ],
  },

  slaughterWeightKg: { broiler: 1.8, cockerel: 2.5 },
  cycleWeeks:        { broiler: 6,   layer: 72, cockerel: 12 },
  productionTracking:{ broiler: 'weight', layer: 'eggs', cockerel: 'weight' },

  slaughterWeightKg: { broiler: 1.8, cockerel: 2.5 },
  cycleWeeks:        { broiler: 6,   layer: 72, cockerel: 12 },
  productionTracking:{ broiler: 'weight', layer: 'eggs', cockerel: 'weight' },

  diseases: [
    {
      name: 'Newcastle Disease',
      aliases: ['ND', 'pseudo fowl pest'],
      urgency: 'CRITICAL',
      affectedAge: 'All ages',
      symptoms: [
        'sudden deaths',
        'twisted neck',
        'paralysis of legs and wings',
        'greenish watery diarrhoea',
        'swollen head',
        'gasping and coughing',
        'loss of appetite',
        'drop in egg production',
      ],
      cause: 'Paramyxovirus — highly contagious, spreads through air, droppings, contaminated equipment',
      treatment: 'No cure. Vaccinate survivors immediately. Isolate and cull severely affected birds.',
      prevention: 'Strict Newcastle vaccination schedule — Lasota at day 7, booster at day 21.',
      callVet: true,
      tip: 'Newcastle can wipe an entire flock in 3 days. If you suspect it, call a vet today — not tomorrow.',
    },
    {
      name: 'Gumboro Disease',
      aliases: ['IBD', 'Infectious Bursal Disease'],
      urgency: 'HIGH',
      affectedAge: '3–6 weeks',
      symptoms: [
        'watery diarrhoea',
        'ruffled feathers',
        'depression and lethargy',
        'loss of appetite',
        'birds sitting hunched',
        'sudden increase in mortality',
        'pecking at their own vent',
      ],
      cause: 'Birnavirus — attacks the immune system. Birds become vulnerable to other diseases.',
      treatment: 'No specific cure. Supportive treatment — electrolytes in water, vitamins, reduce stress.',
      prevention: 'Gumboro vaccine at day 14 and booster at day 28.',
      callVet: false,
      tip: 'Gumboro damages immunity permanently in surviving birds. Vaccinate strictly to prevent it.',
    },
    {
      name: 'Coccidiosis',
      aliases: ['cocci'],
      urgency: 'HIGH',
      affectedAge: '2–8 weeks',
      symptoms: [
        'bloody diarrhoea',
        'ruffled feathers',
        'pale comb',
        'loss of appetite',
        'weight loss',
        'huddling near heat source',
        'lethargy',
      ],
      cause: 'Eimeria parasites in contaminated litter or water. Thrives in wet dirty conditions.',
      treatment: 'Amprolium (Amprolite) in drinking water for 5–7 days. Clean and dry the litter immediately.',
      prevention: 'Use coccidiostat in starter feed. Keep litter dry. Avoid overcrowding.',
      callVet: false,
      tip: 'Bloody droppings = coccidiosis until proven otherwise. Act immediately — it kills fast in young chicks.',
    },
    {
      name: 'Fowl Typhoid',
      aliases: ['salmonella gallinarum'],
      urgency: 'HIGH',
      affectedAge: 'All ages, worse in adults',
      symptoms: [
        'greenish or yellowish diarrhoea',
        'pale shrunken comb',
        'loss of appetite',
        'increased thirst',
        'lethargy',
        'ruffled feathers',
        'sudden deaths in adults',
      ],
      cause: 'Salmonella Gallinarum bacteria. Spreads through contaminated feed, water, and equipment.',
      treatment: 'Enrofloxacin or Tetracycline antibiotics for 5 days. Consult vet for dosage.',
      prevention: 'Buy chicks from disease-free hatcheries. Maintain strict biosecurity.',
      callVet: true,
      tip: 'Fowl Typhoid is a notifiable disease in Nigeria. Vet involvement is important.',
    },
    {
      name: 'Infectious Bronchitis',
      aliases: ['IB', 'bronchitis'],
      urgency: 'MEDIUM',
      affectedAge: 'All ages',
      symptoms: [
        'sneezing and coughing',
        'nasal discharge',
        'watery eyes',
        'gasping',
        'drop in egg production',
        'soft or misshapen eggshells',
        'reduced feed intake',
      ],
      cause: 'Coronavirus — spreads rapidly through air. Worse in cold and poorly ventilated houses.',
      treatment: 'No specific cure. Antibiotics to prevent secondary bacterial infection. Vitamins and electrolytes.',
      prevention: 'Good ventilation. Avoid overcrowding. Some farms vaccinate against IB.',
      callVet: false,
      tip: 'Improve ventilation immediately. Cold damp air makes IB much worse.',
    },
    {
      name: 'Fowl Pox',
      aliases: ['pox', 'chicken pox'],
      urgency: 'MEDIUM',
      affectedAge: 'All ages',
      symptoms: [
        'wart-like scabs on comb and wattles',
        'lesions around eyes and beak',
        'difficulty eating',
        'reduced egg production',
        'weight loss',
        'lethargy',
      ],
      cause: 'Poxvirus — spreads through mosquito bites and direct contact with infected birds.',
      treatment: 'No cure. Remove scabs carefully. Apply iodine to lesions. Supportive care.',
      prevention: 'Fowl Pox vaccine at day 42 (wing web stab method).',
      callVet: false,
      tip: 'Control mosquitoes around your farm — they are the main carrier of Fowl Pox.',
    },
    {
      name: "Marek's Disease",
      aliases: ['mareks'],
      urgency: 'HIGH',
      affectedAge: '6–30 weeks',
      symptoms: [
        'paralysis of legs or wings',
        'one leg forward one leg back posture',
        'weight loss',
        'grey iris or irregular pupil',
        'skin tumours',
        'sudden death',
      ],
      cause: 'Herpesvirus — highly contagious. Spreads through feather dust.',
      treatment: 'No cure. Cull affected birds to prevent spread.',
      prevention: "Marek's vaccine given at hatchery on day 1. Buy only vaccinated chicks.",
      callVet: true,
      tip: "Always ask the hatchery if chicks were vaccinated for Marek's before you buy.",
    },
    {
      name: 'Colibacillosis',
      aliases: ['e.coli', 'ecoli'],
      urgency: 'MEDIUM',
      affectedAge: 'All ages',
      symptoms: [
        'swollen abdomen',
        'nasal discharge',
        'lethargy',
        'ruffled feathers',
        'diarrhoea',
        'sudden deaths in young chicks',
        'reduced growth',
      ],
      cause: 'E. coli bacteria — from contaminated water, feed, or dirty equipment.',
      treatment: 'Antibiotics — Enrofloxacin or Trimethoprim-Sulfa. Clean water source immediately.',
      prevention: 'Clean drinkers daily. Use clean water. Maintain good hygiene in the pen.',
      callVet: false,
      tip: 'E. coli is almost always a hygiene problem. Clean water and clean feeders prevent 90% of cases.',
    },
  ],
};